// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oljwubwhbpgrcejzszkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sand1YndoYnBncmNlanpzemtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzQyNDcsImV4cCI6MjA3NDAxMDI0N30.bYmaaauYA3dONWRfnoIdKR4Oa1dCM7Tb3COuSTFBPaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});